#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # Postgres
    url: jdbc:postgresql://localhost:5432/vols_helper
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  # thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
  # Jackson Serialization Issue Resolver
  #jackson:
  #  visibility:
  #    field: any
  #    getter: none
  #    setter: none
  #    is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  #cache:
   # cache-names: users
    #caffeine.spec: maximumSize=1,expireAfterAccess=60s

logging:
  level:
    root: WARN
    ai.polyakov.volshelper: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

#springdoc.swagger-ui.path: /